source 'https://rubygems.org'

  gem 'rails', '>= 5.0.0.1'
  gem 'pg', '~> 0.18'
  gem 'puma', '~> 3.0'
  gem 'sass-rails', '~> 5.0'
  gem 'uglifier', '>= 1.3.0'
  gem 'jquery-rails'
  gem 'turbolinks', '~> 5'
  gem 'jbuilder', '~> 2.5'
  gem 'paperclip', '~> 4.1'
  # gem 'bootstrap', '~> 4.0.0.alpha6'
  gem 'devise'
  gem 'anjlab-bootstrap-rails', '~> 3.0.0.3', :require => 'bootstrap-rails'
  gem 'byebug', platform: :mri
  gem 'pry'
  gem 'launchy'
  gem 'capybara'
  gem 'simplecov', require: false
  gem 'factory_girl_rails'
  gem 'shoulda-matchers'
  gem 'rspec-rails'
  gem 'letter_opener'
  gem 'poltergeist', '~> 1.10.0'
  gem 'database_cleaner'
  gem 'stripe'
  gem 'geocoder'
  gem 'gmaps4rails'
  gem 'instagram'
  gem 'etsy'
  gem 'dotenv-rails'
  gem 'ckeditor'
  gem 'simple_form'
  gem 'mail_form'
  gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
  gem 'web-console', group: :development
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'coffee-script'

ruby '2.2.2'
